FROM python:3.12
LABEL maintainer="Muhammad-Talha"
WORKDIR /code
RUN pip install poetry
COPY . /code/
RUN poetry config virtualenvs.create false
RUN poetry install
EXPOSE 8000
CMD ["poetry", "run", "uvicorn", "todoapp_backend.main:app", "--host", "0.0.0.0", "--reload"]